language: python
python:
  - "2.6"
  - "2.7"

# command to install dependencies
install:
  - pip install -r requirements-tests.txt

# command to run tests
script:
  - coverage run manage.py test wom_classification
  - coverage run -a manage.py test wom_pebbles
  - coverage run -a manage.py test wom_river
  - coverage run -a manage.py test wom_user

after_success:
  - coveralls

